const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const { createState, transition, applyCommand, readServer, project, OWNER } = require('../utils/cato-sync-contract')
const clone = value => JSON.parse(JSON.stringify(value))
const act = (state, type, deviceId = 'a', rest = {}) => transition(state, { type, deviceId, ...rest })
const client = (state, device = 'a') => state.clients.find(item => item.id === device)
const firstId = state => Object.keys(state.server.records)[0]
function sharedTask() {
  let state = act(createState(), 'create', 'a', { title: '记录饮水情况' })
  return act(state, 'sync', 'b')
}
function conflicted() {
  let state = sharedTask()
  const recordId = firstId(state)
  state = act(state, 'toggleOnline', 'b')
  state = act(state, 'edit', 'b', { recordId, title: 'B 的本地名称' })
  state = act(state, 'complete', 'b', { recordId, completed: true })
  state = act(state, 'edit', 'a', { recordId, title: 'A 的权威端名称' })
  return act(state, 'toggleOnline', 'b')
}
function harness(t) {
  const values = {}
  const driver = {
    failWrite: false, modal: null,
    getStorageSync: key => values[key],
    setStorageSync(key, value) { if (this.failWrite) throw Error('quota'); values[key] = clone(value) },
    showModal(options) { this.modal = options }
  }
  let definition
  global.wx = driver
  global.Page = value => { definition = value }
  const file = require.resolve('../pages/cato-sync-contract/index')
  delete require.cache[file]
  require(file)
  function open() {
    const page = { ...definition, data: clone(definition.data), setData(patch) {
      for (const [key, value] of Object.entries(patch)) {
        const parts = key.split('.')
        let at = this.data
        for (const part of parts.slice(0, -1)) at = at[part]
        at[parts.at(-1)] = clone(value)
      }
    } }
    page.onLoad()
    return page
  }
  t.after(() => { delete global.wx; delete global.Page; delete require.cache[file] })
  return { driver, values, page: open(), open }
}

test('fresh experiment has two distinct replicas and an empty simulated authority', () => {
  const state = createState()
  assert.equal(state.clients.length, 2)
  assert.equal(state.clients[0].userId, state.clients[1].userId)
  assert.notEqual(state.clients[0].records, state.clients[1].records)
  assert.deepEqual(state.server.records, {})
  assert.equal(project(state).clients[0].queue.length, 0)
})
test('create, edit, complete, undo and delete increment versions without mutating input', () => {
  const initial = createState()
  let state = act(initial, 'create', 'a', { title: '  饮水记录  ' })
  const recordId = firstId(state)
  assert.equal(state.server.records[recordId].title, '饮水记录')
  assert.deepEqual(initial, createState())
  state = act(state, 'edit', 'a', { recordId, title: '晚间饮水记录' })
  state = act(state, 'complete', 'a', { recordId, completed: true })
  state = act(state, 'complete', 'a', { recordId, completed: false })
  state = act(state, 'delete', 'a', { recordId })
  assert.deepEqual(state.server.records[recordId], { id: recordId, ownerId: OWNER, version: 5, title: '', completed: false, deleted: true })
  assert.equal(state.server.revision, 5)
  assert.equal(Object.keys(state.server.receipts).length, 5)
})
test('replicas do not silently refresh when another device changes the authority', () => {
  let state = sharedTask()
  const recordId = firstId(state)
  state = act(state, 'edit', 'a', { recordId, title: '新名称' })
  assert.equal(client(state, 'b').records[recordId].version, 1)
  assert.equal(project(state).clients[1].records[0].serverVersion, 2)
  state = act(state, 'sync', 'b')
  assert.equal(client(state, 'b').records[recordId].title, '新名称')
})
test('offline commands chain expected versions and reconnect applies in order', () => {
  let state = act(createState(), 'toggleOnline')
  state = act(state, 'create', 'a', { title: '离线新建' })
  const recordId = Object.keys(client(state).records)[0]
  state = act(state, 'edit', 'a', { recordId, title: '离线修改' })
  state = act(state, 'complete', 'a', { recordId, completed: true })
  assert.deepEqual(client(state).queue.map(command => command.expectedVersion), [0, 1, 2])
  assert.equal(new Set(client(state).queue.map(command => command.id)).size, 3)
  assert.equal(state.server.revision, 0)
  state = act(state, 'toggleOnline')
  assert.equal(state.server.records[recordId].version, 3)
  assert.equal(state.server.records[recordId].completed, true)
  assert.equal(client(state).queue.length, 0)
})
test('lost acknowledgement keeps same command ID and retry does not increment authority twice', () => {
  let state = act(createState(), 'toggleOnline')
  state = act(state, 'create', 'a', { title: '重试测试' })
  const originalCommand = clone(client(state).queue[0])
  state = act(state, 'reconnectLostAck')
  assert.equal(state.server.revision, 1)
  assert.deepEqual(client(state).queue[0], originalCommand)
  state = act(state, 'sync')
  assert.equal(state.server.revision, 1)
  assert.equal(client(state).queue.length, 0)
  assert.match(client(state).lastMessage, /去重 1 条/)
})
test('repeated acknowledgement loss is idempotent across serialized reloads', () => {
  let state = act(act(createState(), 'toggleOnline'), 'create', 'a', { title: '重复回执' })
  state = act(state, 'reconnectLostAck')
  state = act(clone(state), 'reconnectLostAck')
  assert.equal(state.server.revision, 1)
  assert.equal(client(state).queue.length, 1)
  state = act(clone(state), 'sync')
  assert.equal(state.server.revision, 1)
})
test('stale version exposes conflict snapshots, keeps queue, and blocks silent writes', () => {
  const state = conflicted()
  const before = clone(state)
  const b = client(state, 'b')
  assert.equal(b.conflict.code, 'CONFLICT')
  assert.equal(b.conflict.local.version, 3)
  assert.equal(b.conflict.remote.version, 2)
  assert.equal(b.queue.length, 2)
  assert.equal(state.server.revision, 2)
  assert.throws(() => act(state, 'create', 'b', { title: '不能偷偷越过冲突' }), /先明确解决/)
  assert.deepEqual(state, before)
})
test('keep remote discards all dependent commands for conflicting record only', () => {
  let state = conflicted()
  const serverBefore = clone(state.server)
  state = act(state, 'resolve', 'b', { choice: 'remote' })
  assert.deepEqual(state.server, serverBefore)
  assert.equal(client(state, 'b').queue.length, 0)
  assert.equal(client(state, 'b').records[firstId(state)].title, 'A 的权威端名称')
  assert.equal(client(state, 'b').conflict, null)
  assert.equal(client(state, 'b').lastConflict.resolution, '已明确保留权威端')
})
test('resubmit local squashes intent, allocates new ID and uses latest authority version', () => {
  let state = conflicted()
  const oldIds = client(state, 'b').queue.map(command => command.id)
  state = act(state, 'resolve', 'b', { choice: 'local' })
  const record = state.server.records[firstId(state)]
  assert.equal(record.version, 3)
  assert.equal(record.title, 'B 的本地名称')
  assert.equal(record.completed, true)
  assert.equal(client(state, 'b').queue.length, 0)
  for (const id of oldIds) assert.equal(state.server.receipts[id], undefined)
  const lastReceipt = Object.values(state.server.receipts).at(-1)
  assert.equal(JSON.parse(lastReceipt.signature)[4], 2)
})
test('resolving one record preserves unrelated queued work and its local preview', () => {
  let state = sharedTask()
  const recordId = firstId(state)
  state = act(state, 'toggleOnline', 'b')
  state = act(state, 'edit', 'b', { recordId, title: '冲突草稿' })
  state = act(state, 'create', 'b', { title: '独立事项' })
  const independentId = client(state, 'b').queue[1].recordId
  state = act(state, 'edit', 'a', { recordId, title: '在线变更' })
  state = act(state, 'toggleOnline', 'b')
  state = act(state, 'resolve', 'b', { choice: 'remote' })
  assert.equal(client(state, 'b').queue.length, 1)
  assert.equal(client(state, 'b').queue[0].recordId, independentId)
  assert.equal(client(state, 'b').records[independentId].title, '独立事项')
  state = act(state, 'sync', 'b')
  assert.equal(state.server.records[independentId].title, '独立事项')
})
test('explicit local deletion can resolve a concurrent remote edit using a new version', () => {
  let state = sharedTask()
  const recordId = firstId(state)
  state = act(state, 'toggleOnline', 'b')
  state = act(state, 'delete', 'b', { recordId })
  state = act(state, 'edit', 'a', { recordId, title: '在线修改' })
  state = act(state, 'toggleOnline', 'b')
  assert.equal(client(state, 'b').conflict.code, 'CONFLICT')
  state = act(state, 'resolve', 'b', { choice: 'local' })
  assert.equal(state.server.records[recordId].deleted, true)
  assert.equal(state.server.records[recordId].version, 3)
})
test('offline create followed by delete delivers an ordered tombstone', () => {
  let state = act(act(createState(), 'toggleOnline'), 'create', 'a', { title: '离线后又删除' })
  const recordId = Object.keys(client(state).records)[0]
  state = act(state, 'delete', 'a', { recordId })
  state = act(state, 'toggleOnline')
  assert.equal(state.server.records[recordId].deleted, true)
  assert.equal(state.server.records[recordId].version, 2)
  assert.equal(client(state).queue.length, 0)
})
test('resubmission bases on current server, not old conflict snapshot', () => {
  let state = conflicted()
  const recordId = firstId(state)
  state = act(state, 'edit', 'a', { recordId, title: '冲突后再次更新' })
  assert.equal(client(state, 'b').conflict.remote.version, 2)
  state = act(state, 'resolve', 'b', { choice: 'local' })
  assert.equal(state.server.records[recordId].version, 4)
  assert.equal(state.server.records[recordId].title, 'B 的本地名称')
})
test('delete tombstone blocks stale edits and explicit overwrite; a new task gets a different ID', () => {
  let state = sharedTask()
  const recordId = firstId(state)
  state = act(state, 'toggleOnline', 'b')
  state = act(state, 'edit', 'b', { recordId, title: '不该复活' })
  state = act(state, 'delete', 'a', { recordId })
  state = act(state, 'toggleOnline', 'b')
  assert.equal(client(state, 'b').conflict.code, 'DELETED')
  assert.equal(project(state).clients[1].canResubmit, false)
  assert.throws(() => act(state, 'resolve', 'b', { choice: 'local' }), /墓碑不可恢复/)
  state = act(state, 'resolve', 'b', { choice: 'remote' })
  state = act(state, 'create', 'b', { title: '新的记录' })
  assert.equal(state.server.records[recordId].deleted, true)
  assert.equal(Object.values(state.server.records).filter(item => !item.deleted).length, 1)
})
test('retrying an old accepted create receipt after deletion cannot resurrect a record', () => {
  let state = act(act(createState(), 'toggleOnline'), 'create', 'a', { title: '旧命令' })
  const command = clone(client(state).queue[0])
  state = act(state, 'toggleOnline')
  state = act(state, 'delete', 'a', { recordId: command.recordId })
  const outcome = applyCommand(state.server, OWNER, command)
  assert.equal(outcome.result.duplicate, true)
  assert.equal(outcome.server.records[command.recordId].deleted, true)
  assert.equal(outcome.server.revision, 2)
})
test('authority rejects read/write from another user before exposing records or receipts', () => {
  let state = act(act(createState(), 'toggleOnline'), 'create', 'a', { title: '仅限本人' })
  const command = clone(client(state).queue[0])
  state = act(state, 'toggleOnline')
  assert.deepEqual(readServer(state.server, 'demo-other-user'), { code: 'DENIED', records: {} })
  const denied = applyCommand(state.server, 'demo-other-user', { ...command, actorId: 'demo-other-user' })
  assert.equal(denied.result.code, 'DENIED')
  assert.equal(denied.result.record, undefined)
  assert.equal(denied.server, state.server)
  assert.equal(applyCommand(state.server, OWNER, { ...command, actorId: 'demo-other-user' }).result.code, 'DENIED')
  assert.match(act(state, 'permissionProbe').permissionResult, /读取已拒绝.*0 条/)
})
test('same command ID with changed content is rejected rather than treated as retry', () => {
  let state = act(act(createState(), 'toggleOnline'), 'create', 'a', { title: '首次内容' })
  const command = clone(client(state).queue[0])
  state = act(state, 'toggleOnline')
  command.payload.title = '冒用同一 ID'
  const outcome = applyCommand(state.server, OWNER, command)
  assert.equal(outcome.result.code, 'ID_REUSE')
  assert.equal(outcome.server.revision, 1)
})
test('invalid titles, types, versions, device IDs and operations preserve original state', () => {
  const state = createState()
  for (const value of ['', '   ', '长'.repeat(81), null, 42]) assert.throws(() => act(state, 'create', 'a', { title: value }), /事项名称/)
  assert.throws(() => act(state, 'create', 'z', { title: 'test' }), /设备/)
  assert.throws(() => act(state, 'complete', 'a', { recordId: 'missing', completed: 'yes' }), /完成状态/)
  assert.throws(() => act(state, 'delete', 'a', { recordId: 'missing' }), /不存在/)
  assert.throws(() => act(state, 'resolve', 'a', { choice: 'remote' }), /没有待解决/)
  assert.throws(() => act(state, 'unknown'), /未知/)
  const base = { id: 'cmd-a-1', actorId: OWNER, deviceId: 'a', recordId: 'task-1', type: 'create', expectedVersion: 0, payload: { title: 'ok', completed: false } }
  for (const patch of [{ expectedVersion: -1 }, { expectedVersion: 1.5 }, { id: '__proto__' }, { type: 'restore' }, { payload: null }]) {
    assert.equal(applyCommand(state.server, OWNER, { ...base, ...patch }).result.code, 'INVALID')
  }
  assert.deepEqual(state, createState())
})
test('offline queue is bounded and offline sync cannot modify authority', () => {
  let state = act(act(createState(), 'toggleOnline'), 'create', 'a', { title: '队列上限' })
  const recordId = Object.keys(client(state).records)[0]
  assert.throws(() => act(state, 'sync'), /设备离线/)
  for (let i = 1; i < 100; i += 1) state = act(state, 'edit', 'a', { recordId, title: '队列 ' + i })
  assert.equal(client(state).queue.length, 100)
  assert.throws(() => act(state, 'edit', 'a', { recordId, title: '超出' }), /最多 100/)
  assert.equal(state.server.revision, 0)
})
test('discard unconfirmed queue does not undo authority after lost acknowledgement', () => {
  let state = act(act(createState(), 'toggleOnline'), 'create', 'a', { title: '已收到但回执丢失' })
  state = act(state, 'reconnectLostAck')
  const authority = clone(state.server)
  state = act(state, 'discardQueue')
  assert.equal(client(state).queue.length, 0)
  assert.deepEqual(state.server, authority)
  assert.deepEqual(client(state).records, authority.records)
})
test('page persistence failure preserves in-memory and saved state, and retries once', t => {
  const h = harness(t)
  h.page.commit({ type: 'create', deviceId: 'a', title: '已保存' })
  const before = clone(h.page._state)
  const storedBefore = clone(h.values)
  h.driver.failWrite = true
  assert.equal(h.page.commit({ type: 'edit', deviceId: 'a', recordId: firstId(before), title: '尚未保存' }), false)
  assert.deepEqual(h.page._state, before)
  assert.deepEqual(h.values, storedBefore)
  assert.equal(h.page.data.retryAvailable, true)
  assert.equal(h.open()._state.server.revision, 1)
  h.driver.failWrite = false
  h.page.retrySave()
  assert.equal(h.page._state.server.revision, 2)
  assert.equal(h.page.data.retryAvailable, false)
  assert.equal(h.open()._state.server.records[firstId(before)].title, '尚未保存')
  assert.deepEqual(Object.keys(h.values), ['catai_cato_lab_v1:sync-contract:state'])
})
test('failed reconnect persistence retains offline queue; retry commits authority only once', t => {
  const h = harness(t)
  h.page.commit({ type: 'toggleOnline', deviceId: 'a' })
  h.page.commit({ type: 'create', deviceId: 'a', title: '离线保存' })
  h.page.armFailure()
  assert.equal(h.page.commit({ type: 'toggleOnline', deviceId: 'a' }), false)
  assert.equal(h.page._state.server.revision, 0)
  assert.equal(client(h.page._state).queue.length, 1)
  assert.equal(client(h.page._state).online, false)
  h.page.retrySave()
  assert.equal(h.page._state.server.revision, 1)
  assert.equal(client(h.page._state).queue.length, 0)
  assert.equal(h.open()._state.server.revision, 1)
})
test('page deletion and edit cancellation do not change records or storage', t => {
  const h = harness(t)
  h.page.commit({ type: 'create', deviceId: 'a', title: '取消测试' })
  const before = clone(h.page._state)
  const event = { currentTarget: { dataset: { device: 'a', record: firstId(before) } } }
  h.page.deleteTask(event)
  h.driver.modal.success({ confirm: false })
  h.page.editTask(event)
  h.page.editTitle({ detail: { value: '放弃草稿' } })
  h.page.cancelEdit()
  assert.deepEqual(h.page._state, before)
  assert.equal(h.page.data.editing, null)
})
test('reload preserves conflicts, offline modes, tombstones and receipts', t => {
  const h = harness(t)
  const state = conflicted()
  h.driver.setStorageSync('catai_cato_lab_v1:sync-contract:state', state)
  const reopened = h.open()
  assert.deepEqual(reopened._state, state)
  assert.equal(reopened.data.clients[1].lastConflict.code, 'CONFLICT')
})
test('invalid persisted schema is not overwritten during page load', t => {
  const h = harness(t)
  h.driver.setStorageSync('catai_cato_lab_v1:sync-contract:state', { schema: 999 })
  const page = h.open()
  assert.equal(page.data.ready, false)
  assert.match(page.data.error, /未覆盖原记录/)
  assert.deepEqual(h.values['catai_cato_lab_v1:sync-contract:state'], { schema: 999 })
})
test('entry, simulated labels and flexible touch/safe-area styles are wired', () => {
  const root = path.resolve(__dirname, '..')
  const config = require('../config/cato-lab')
  assert.equal(config.variant, 'sync-contract')
  assert.equal(config.entry, '/pages/cato-sync-contract/index')
  const app = JSON.parse(fs.readFileSync(path.join(root, 'app.json'), 'utf8'))
  assert.ok(app.pages.includes(config.entry.slice(1)))
  const markup = fs.readFileSync(path.join(root, 'pages/cato-sync-contract/index.wxml'), 'utf8')
  assert.match(markup, /SIMULATED/)
  assert.match(markup, /不是真实多端同步/)
  assert.match(markup, /expectedVersion/)
  assert.match(markup, /最近一次冲突/)
  const styles = fs.readFileSync(path.join(root, 'styles/cato-lab.wxss'), 'utf8')
  assert.match(styles, /min-height: 88rpx/)
  assert.match(styles, /safe-area-inset-bottom/)
})
