'use strict'
// Local synthetic role-flow smoke through real WeChat Page controllers, not touch/keyboard testing.
// Requires a fresh social-followup experiment. Never clears existing data implicitly.
const path = require('node:path')
const assert = require('node:assert/strict')
const [automatorDir, port] = process.argv.slice(2)
const event = data => ({ currentTarget: { dataset: data } })
async function main() {
  const Launcher = require(path.join(path.resolve(automatorDir), 'out/Launcher')).default
  const mini = await new Launcher().connectTool({ wsEndpoint: 'ws://127.0.0.1:' + port })
  try {
    const state = await mini.evaluate(() => ({ offline: getApp().globalData.catoLabOffline, cloudReady: getApp().globalData.cloudReady }))
    assert.equal(state.offline, true); assert.equal(state.cloudReady, false)
    let page = await mini.reLaunch('/pages/cato-social-followup/index')
    let data = await page.data()
    assert.equal(data.comments.length, 0, 'requires fresh synthetic storage; reset only this experiment manually')
    assert.equal(data.contact, null)
    await page.callMethod('fillOpener')
    assert.equal((await page.data()).comments.length, 0, 'opener must not send')
    await page.callMethod('sendComment')
    assert.equal((await page.data()).comments.length, 1)
    await page.callMethod('switchRole', event({ id: 'lin' }))
    data = await page.data()
    await page.callMethod('openNotice', event({ id: data.notices.find(item => item.kind === 'comment').id }))
    assert.equal((await page.data()).focusId, data.comments[0].id)
    await page.callMethod('inputComment', { detail: { value: '本机测试回复：它每天都会来看树影。' } })
    await page.callMethod('sendComment')
    await page.callMethod('switchRole', event({ id: 'momo' }))
    data = await page.data()
    await page.callMethod('openNotice', event({ id: data.notices.find(item => item.kind === 'reply').id }))
    assert.equal((await page.data()).storyId, 'window')
    await page.callMethod('openChat')
    await page.callMethod('fillGreeting')
    await page.callMethod('sendMessage')
    data = await page.data()
    assert.equal(data.messages.length, 1); assert.equal(data.contact.status, 'pending'); assert.equal(data.permission.allowed, false)
    await page.callMethod('inputMessage', { detail: { value: '这条第二招呼应被阻止。' } })
    await page.callMethod('sendMessage')
    assert.equal((await page.data()).messages.length, 1)
    assert.ok((await page.data()).error)
    await page.callMethod('switchRole', event({ id: 'lin' }))
    data = await page.data()
    await page.callMethod('openNotice', event({ id: data.notices.find(item => item.kind === 'message').id }))
    assert.equal((await page.data()).stage, 'chat')
    await page.callMethod('fillGreeting'); await page.callMethod('sendMessage')
    data = await page.data()
    assert.equal(data.contact.status, 'open'); assert.equal(data.messages.length, 2)
    await page.callMethod('switchRole', event({ id: 'momo' }))
    await page.callMethod('fillGreeting'); await page.callMethod('sendMessage')
    assert.equal((await page.data()).messages.length, 3)
    await page.callMethod('toggleBlock')
    await page.callMethod('inputMessage', { detail: { value: '拉黑后这条消息也应被阻止。' } })
    await page.callMethod('sendMessage')
    assert.equal((await page.data()).messages.length, 3)
    page = await mini.reLaunch('/pages/cato-social-followup/index')
    data = await page.data()
    assert.equal(data.ownBlock, true); assert.equal(data.messages.length, 3)
    console.log(JSON.stringify({ passed: true, mode: 'real IDE Page.callMethod, synthetic local data only', assertions: ['editable opener does not send', 'comment/reply notifications route to original context', 'second stranger greeting blocked', 'recipient reply opens conversation', 'block prevents sending', 'relaunch retains local state'], limitations: 'Not physical taps, keyboard, real accounts, network or production permissions.' }, null, 2))
  } finally { mini.disconnect() }
}
main().catch(error => { console.error(error.message); process.exitCode = 1 })
